from PySide2.QtWidgets import *
from PySide2.QtGui import *
from PySide2.QtCore import *
import sys
from calculatorBrain import Brain

class Calculator(QWidget):
    def __init__(self):
        super().__init__()

        appIcon = QIcon("icon1.png")
        self.setWindowIcon(appIcon)

        self.screen = QLineEdit('', self)
        self.screen.setAlignment(Qt.AlignRight)
        self.screen.setMaxLength(100)
        self.screen.setReadOnly(True)
        text = self.screen.font()
        text.setPointSize(text.pointSize() + 20)
        self.screen.setFont(text)
        self.screen.setStyleSheet('QLineEdit {color: rgb(0, 0, 0);}')

        self.calculatorBrain = Brain(self.screen)
        self.createGridLayout()


    def createGridLayout(self):

        gridLayout = QGridLayout()
        gridLayout.addWidget(self.screen, 1, 1, 1, -1)
        self.setLayout(gridLayout)
 
        self.button0 = QPushButton('0')
        self.button0.clicked.connect(lambda: self.calculatorBrain.buttonPress('0'))
        self.button1 = QPushButton('1')
        self.button1.clicked.connect(lambda: self.calculatorBrain.buttonPress('1'))
        self.button2 = QPushButton('2')
        self.button2.clicked.connect(lambda: self.calculatorBrain.buttonPress('2'))
        self.button3 = QPushButton('3')
        self.button3.clicked.connect(lambda: self.calculatorBrain.buttonPress('3'))
        self.button4 = QPushButton('4')
        self.button4.clicked.connect(lambda: self.calculatorBrain.buttonPress('4'))
        self.button5 = QPushButton('5')
        self.button5.clicked.connect(lambda: self.calculatorBrain.buttonPress('5'))
        self.button6 = QPushButton('6')
        self.button6.clicked.connect(lambda: self.calculatorBrain.buttonPress('6'))
        self.button7 = QPushButton('7')
        self.button7.clicked.connect(lambda: self.calculatorBrain.buttonPress('7'))
        self.button8 = QPushButton('8')
        self.button8.clicked.connect(lambda: self.calculatorBrain.buttonPress('8'))
        self.button9 = QPushButton('9')
        self.button9.clicked.connect(lambda: self.calculatorBrain.buttonPress('9'))
        self.buttonDecimal = QPushButton('.')
        self.buttonDecimal.clicked.connect(lambda: self.calculatorBrain.buttonPress('.'))
        self.buttonEquals = QPushButton('=')
        self.buttonEquals.clicked.connect(lambda: self.calculatorBrain.buttonPress('='))
        self.buttonDivide = QPushButton('/')
        self.buttonDivide.clicked.connect(lambda: self.calculatorBrain.buttonPress('/'))
        self.buttonX = QPushButton('X')
        self.buttonX.clicked.connect(lambda: self.calculatorBrain.buttonPress('X'))
        self.buttonMinus = QPushButton('-')
        self.buttonMinus.clicked.connect(lambda: self.calculatorBrain.buttonPress('-'))
        self.buttonPlus = QPushButton('+')
        self.buttonPlus.clicked.connect(lambda: self.calculatorBrain.buttonPress('+'))
        self.buttonClear = QPushButton('C')
        self.buttonClear.clicked.connect(lambda: self.calculatorBrain.buttonPress(''))
        self.buttonClear.setFont(QFont('Sanserif', 14))
        self.buttonClear.setStyleSheet('QPushButton {font-weight: bold; background-color:#FF9C87}')
 
        self.buttonClear.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonClear, 2, 3, 1, 2)
        self.button7.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button7, 3, 1)
        self.button8.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button8, 3, 2)
        self.button9.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button9, 3, 3)
        self.buttonDivide.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonDivide, 3, 4)
        self.button4.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button4, 4, 1)
        self.button5.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button5, 4, 2)
        self.button6.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button6, 4, 3)
        self.buttonX.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonX, 4, 4)
        self.button1.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button1, 5, 1)
        self.button2.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button2, 5, 2)
        self.button3.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button3, 5, 3)
        self.buttonMinus.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonMinus, 5, 4)
        self.button0.setMinimumSize(50, 50)
        gridLayout.addWidget(self.button0, 6, 1)
        self.buttonDecimal.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonDecimal, 6, 2)
        self.buttonEquals.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonEquals, 6, 3)
        self.buttonPlus.setMinimumSize(50, 50)
        gridLayout.addWidget(self.buttonPlus, 6, 4)